language: android

android:
  components:
    - tools
    - build-tools-24.0.3
    - android-25
    - extra-android-support
    - extra-android-m2repository

  script:
    - ./gradlew clean :app:testDebugUnitTest

  notifications:
    email: false

jdk:
  - oraclejdk8

sudo: false
